FROM node:20-alpine3.20
WORKDIR /usr/src/app

RUN apk update && apk add --no-cache \
    git \
    vim \
    tree \
    curl \
    wget

# package.jsonとpackage-lock.jsonをコピー
COPY package*.json ./

RUN npm install

# 残りのアプリケーションコードをコピー
COPY . .

CMD ["npx", "json-server", "--watch", "db.json", "--port", "4001"]
