version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"  # Reactアプリケーション
      - "6006:6006"  # Storybook
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev 